#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

start_service() {
    procd_open_instance "KMS-daemon"
    # Run vlmcsd in foreground, log verbosely to stdout.
    procd_set_param command /usr/bin/vlmcsd -veD 
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_close_instance
}
