# Generated by Bing GPT.
# Use an official Python runtime as a parent image
FROM python:3-alpine

# Change the working directory to the homelab-infra directory
WORKDIR /app/homelab-infra

# Copy the homelab-infra repository into the container
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run register_dns.py when the container launches
ENTRYPOINT ["python", "util-cookbook/tencent-cloud/register_dns.py"]