# Generated by Bing GPT.
# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

# Clone the homelab-infra repository into the container
RUN git clone https://github.com/lirundong/homelab-infra.git

# Change the working directory to the homelab-infra directory
WORKDIR /app/homelab-infra

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run register_dns.py when the container launches
CMD ["python", "util-cookbook/tencent-cloud/register_dns.py", "-h"]