#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

start_service() {
    procd_open_instance "NaiveProxy"
    # Run naive proxy in foreground, log to stdout.
    procd_set_param command /usr/bin/naive /root/.config/naiveproxy/config.json
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_close_instance
}
