# Source configuration that generates Clash and Quantumult X configs.
subscriptions:
- name: V2Club
  type: clash
  url: '@secret:SUBSCRIPTION_URL'
proxies:
- name: 🇯🇵「V2ray」bwh-jp-01
  type: vmess
  server: '@secret:NODE_HOSTNAME'
  port: 443
  uuid: '@secret:NODE_V2RAY_UUID'
  alterId: 0
  cipher: none
  tls: true
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: '@secret:NODE_V2RAY_WS_PATH'
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
  udp: true
- name: 🇯🇵「SS-AES」bwh-jp-01
  type: ss
  server: '@secret:NODE_HOSTNAME'
  port: '@secret:NODE_SS_AES_PORT!int'
  cipher: aes-128-gcm
  password: '@secret:NODE_SS_AES_PASSWORD'
  udp: true
- name: &ss-chacha-jp-01 🇯🇵「SS-ChaCha」bwh-jp-01
  type: ss
  server: '@secret:NODE_HOSTNAME'
  port: '@secret:NODE_SS_CHACHA_PORT!int'
  cipher: chacha20-ietf-poly1305
  password: '@secret:NODE_SS_CHACHA_PASSWORD'
  udp: true
rules:
- name: Guard
  type: select
  filters:
  - type: DOMAIN
    arg: '@secret:NODE_HOSTNAME'
  - type: DOMAIN-KEYWORD
    arg: v2clubnode
  - type: PROCESS-NAME
    arg: qBittorrent
  - type: quantumult
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Unbreak.list
  img-url: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Hijacking.png
  proxies:
  - DIRECT
- name: AdBlock
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/AdBlock.list
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/AdBlock.png
  proxies:
  - REJECT
  - Mainland
- name: Netflix
  type: select
  filters:
  - type: quantumult
    url: https://github.com/GeQ1an/Rules/raw/master/QuantumultX/Filter/Optional/Netflix.list
  # Weird tests on Netflix web.
  - type: DOMAIN-SUFFIX
    arg: cookielaw.org
  - type: DOMAIN-SUFFIX
    arg: onetrust.com
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Netflix.png
  proxies:
  - Outside
  - type: regex
    pattern: SG|Singapore|新加坡|🇸🇬
- name: Telegram
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Extra/Telegram/Telegram.list
  img-url: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Telegram.png
  proxies:
  - Outside
  - type: regex
    pattern: SG|Singapore|新加坡|🇸🇬
- name: Outside
  type: select
  filters:
  - type: DOMAIN-SUFFIX
    arg: s1s1s1.com
  - type: DOMAIN-SUFFIX
    arg: sehuatang.net
  - type: DOMAIN-KEYWORD
    arg: linkedin
  - type: quantumult
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Global.list
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Outside.png
  proxies:
  - PROXY
- name: Bilibili & iQIYI
  type: select
  filters:
  - type: clash-classic
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
  img-url: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/iQIYI%26bilibili.png
  proxies:
  - Mainland
  - type: regex
    pattern: HK|HongKong|香港|🇭🇰|TW|Taiwan|台湾|🇹🇼
- name: Microsoft
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Optional/Microsoft.list
  - type: DOMAIN-SUFFIX
    arg: sharepoint.com
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Microsoft.png
  proxies:
  - Mainland
  - Outside
- name: Apple
  type: select
  filters:
  - type: quantumult
    url: https://github.com/GeQ1an/Rules/raw/master/QuantumultX/Filter/Apple.list
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Apple.png
  proxies:
  - Mainland
  - Outside
- name: Speedtest
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Speedtest.list
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Speedtest.png
  proxies:
  - Mainland
  - Outside
- name: Mainland
  type: select
  filters:
  - type: DOMAIN-SUFFIX
    arg: cn
  - type: DOMAIN-KEYWORD
    arg: nvidia
  - type: DOMAIN-KEYWORD
    arg: nvda
  - type: DOMAIN-KEYWORD
    arg: slack
  - type: quantumult
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/China.list
  - type: geoip
    arg: CN
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Mainland.png
  proxies:
  - DIRECT
- name: Others
  type: select
  filters:
  - type: match
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Others.png
  proxies:
  - PROXY
  - DIRECT
rewrites:
- name: General
  type: quantumult
  url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/General.conf
- name: AdBlock
  type: quantumult
  url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/Advertising.conf
generates:
- name: clash
  type: clash
  allow-lan: false
  ipv6: true
  socks-port: 10080
  port: 10081
- name: clash-daemon
  type: clash
  allow-lan: true
  ipv6: true
  socks-port: 10080
  port: 10081
  redir-port: 10082
  tproxy-port: 10083
  external-ui: clash-dashboard
  external-controller: :9090
  secret: '@secret:CLASH_SECRET'
  authentication:
  - '@secret:CLASH_PROXY_USERNAME:@secret:CLASH_PROXY_PASSWORD'
  dns: &DNS_CONFIG
    enable: true
    listen: :10053
    ipv6: true
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
    - '+.local'
    - localhost.ptlogin2.qq.com
    - '@secret:NODE_HOSTNAME'
    # Otherwise MS apps and network manager will not operate properly.
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
    # Otherwise IPv6 address acquisition will not operate properly.
    - api6.ipify.org
    nameserver:
    - 127.0.0.1
  tun:
    enable: true
    stack: system
    dns-hijack:
    - tcp://1.1.1.1:53
    - tcp://1.0.0.1:53
    - tcp://8.8.4.4:53
    - tcp://8.8.8.8:53
    - tcp://9.9.9.9:53
    - tcp://149.112.112.112:53
    - tcp://35.190.88.7:53
    - tcp://[2001:4860:4860::8888]:53
    - tcp://[2001:4860:4860::8844]:53
    - tcp://[2606:4700:4700::1111]:53
    - tcp://[2606:4700:4700::1001]:53
    - tcp://[2620:fe::fe]:53
    - tcp://[2620:fe::9]:53
  profile:
    store-selected: true
    store-fake-ip: true
- name: clash-android
  type: clash
  allow-lan: false
  ipv6: true
  socks-port: 10080
  port: 10081
  dns: *DNS_CONFIG
- name: quantumult-x
  type: quantumult
  general:
    excluded_routes:
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    - 17.0.0.0/8
    geo_location_checker:
    - http://ip-api.com/json/?lang=zh-CN
    - https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/IP_API.js
    server_check_url: http://cp.cloudflare.com/generate_204
    ssid_suspended_list:
    - Rundong's AP
    - Rundong's AP 5GHz
    fallback_udp_policy: *ss-chacha-jp-01
  task_local:
  - name: 流媒体-解锁查询
    type: event-interaction
    url: https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/streaming-ui-check.js
    img-url: checkmark.seal.system
  - name: GeoIP 查询
    type: event-interaction
    url: https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/geo_location.js
    img-url: location.fill.viewfinder.system
