name: Stable Monthly
on:
  push:
  schedule:
  - cron: '30 9 1 * *'  # Monthly build.
jobs:
  build-openwrt-stable:
    name: OpenWRT stable monthly build
    if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup-dependencies
      run: |
        pip3 install --user --upgrade cryptography emoji pycountry pytz pyyaml requests
    - name: build-openwrt-22-03
      env:
        PASSWORD: ${{ secrets.MASTER_PASSWORD }}
        TARGET: x86/64
        VERSION: '22.03.4'
        REPOSITORY: https://downloads.openwrt.org
        GCC_VERSION: 11.2.0_musl
      run: |
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        bash openwrt-builder/build.sh
        cp -r /tmp/openwrt/openwrt-imagebuilder-$VERSION-${TARGET/\//-}.Linux-${TARGET/\//_}/bin/targets/$TARGET artifacts-$VERSION
        for f in $(find artifacts-$VERSION -iname '*.gz'); do
          gpg -c --batch --yes --passphrase=${PASSWORD} $f
          rm $f
        done
    - name: upload-openwrt-22-03-artifacts
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-stable-${{ env.VERSION }}
        path: artifacts-${{ env.VERSION }}
